### ISSUE TITLE
TypeError: huaweiLteApi.Diagnosis is not a constructor

### ISSUE THREAD

**Issue by rusak47** [Salamek/huawei-lte-api-ts#7]
Hello!
Recently i became an owner or Huawei router and found out that our network coverage has some flaws. Luckily Huawei has API and thanks to you it's possible to use via relatively simple language - typescript. However, i'm new to it and have some problems.

Comparing DialUp and Diagnosis types i don't see a big difference, but trying to call Diagnosis the same as DialUp in example i receive  TypeError. Could you, please, post some working examples calling other types, like Diagnosis, etc. Any help will be appreciated.

```
$ node --trace-warnings test02.js 
Ready
(node:53367) UnhandledPromiseRejectionWarning: TypeError: huaweiLteApi.Diagnosis is not a constructor
    at /home/ubuntu/test02.js:17:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:53367) TypeError: huaweiLteApi.Diagnosis is not a constructor
    at /home/ubuntu/test02.js:17:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:53367) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

```
const dialUp = new huaweiLteApi.DialUp(connection); //working fine
    const diag = new huaweiLteApi.Diagnosis(connection);   //error

```

**Comment by rusak47** [comment]
I suppose i have found out the reason of error: those classes doesnt event exist in npm version:
```
$ ls node_modules/huawei-lte-api/dist/api/            
Device.d.ts  Device.js  DialUp.d.ts  DialUp.js  User.d.ts  User.js
```
And class definition differs from those i've seen here. Why is that and how to fix missing files problem?

**Comment by rusak47** [comment]
Problem solved by cloning git version of huawei-api port and building it.
